In [1]:
import pandas as pd
import numpy as np

In [2]:
import geopandas as gpd
import folium 
import os

In [3]:
import polars as pl

In [4]:
# Load datasets
path = '../dataset/'
train_path = os.path.join(path, 'Train.csv')
test_path = os.path.join(path, 'Test.csv')
gap_train_path = os.path.join(path, 'Gap_Train.csv')
gap_test_path = os.path.join(path, 'Gap_Test.csv')
sample_submission_path = os.path.join(path, 'SampleSubmission.csv')

train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)
train_gap_df = pd.read_csv(gap_train_path)
test_gap_df = pd.read_csv(gap_test_path)
sample_submission = pd.read_csv(sample_submission_path)

In [5]:
# Load datasets
path2 = '../processed_data/'
landsat8 = os.path.join(path2, 'processed_landsat8.parquet')
landsat8_df = pl.read_parquet(landsat8)

landsat8_df.head(5)

shape: (5, 7)
┌───────────┬─────────────┬──────────┬──────────┬──────────┬───────────┬──────────┐
│ PID       ┆ LST_Celsius ┆ NDVI_ls8 ┆ EVI_ls8  ┆ SAVI_ls8 ┆ NDWI_ls8  ┆ BSI_ls8  │
│ ---       ┆ ---         ┆ ---      ┆ ---      ┆ ---      ┆ ---       ┆ ---      │
│ str       ┆ f64         ┆ f64      ┆ f64      ┆ f64      ┆ f64       ┆ f64      │
╞═══════════╪═════════════╪══════════╪══════════╪══════════╪═══════════╪══════════╡
│ ID_7aZMWw ┆ -273.031323 ┆ 0.196687 ┆ 0.000013 ┆ 0.000016 ┆ -0.063934 ┆ 0.166449 │
│ ID_7aZMWw ┆ -273.031213 ┆ 0.250841 ┆ 0.000015 ┆ 0.000018 ┆ -0.021971 ┆ 0.129793 │
│ ID_7aZMWw ┆ -273.03165  ┆ 0.238409 ┆ 0.000018 ┆ 0.000021 ┆ -0.013549 ┆ 0.116166 │
│ ID_BieBEw ┆ -273.032992 ┆ 0.187991 ┆ 0.000016 ┆ 0.00002  ┆ -0.031235 ┆ 0.144392 │
│ ID_BieBEw ┆ -273.033663 ┆ 0.191971 ┆ 0.000019 ┆ 0.000023 ┆ -0.0308   ┆ 0.14179  │
└───────────┴─────────────┴──────────┴──────────┴──────────┴───────────┴──────────┘

In [6]:
modis_mcd43a4 = os.path.join(path2, 'processed_modis_mcd43a4.parquet')
modis_mcd43a4df = pl.read_parquet(modis_mcd43a4)

modis_mcd43a4df.head(5)

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ PID       ┆ NDVI_mcd4 ┆ EVI_mcd43 ┆ SAVI_mcd4 ┆ … ┆ Brightnes ┆ Red_Green ┆ Chlorophy ┆ Blue_NIR │
│ ---       ┆ 3a4       ┆ a4        ┆ 3a4       ┆   ┆ s_Index_m ┆ _Ratio_mc ┆ ll_Index_ ┆ _Ratio_m │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ cd43a4    ┆ d43a4     ┆ mcd43a4   ┆ cd43a4   │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ID_I5RGjv ┆ 0.186781  ┆ 0.000026  ┆ 0.000031  ┆ … ┆ 0.00002   ┆ 1.412175  ┆ -0.291872 ┆ 0.287385 │
│ ID_8jWzJ5 ┆ 0.185201  ┆ 0.000021  ┆ 0.000026  ┆ … ┆ 0.000017  ┆ 1.516103  ┆ -0.340414 ┆ 0.270172 │
│ ID_d009mj ┆ 0.205554  ┆ 0.000023  ┆ 0.000027  ┆ … ┆ 0.000016  ┆ 1.360094  ┆ -0.264756 ┆ 0.301737 │
│ ID_2ymCjP ┆ 0.202991  ┆ 0.000024  ┆ 0.000028  ┆ … ┆ 0.000017  ┆ 1.50768   ┆ -0.336729 ┆ 0.260036 │
│ ID_YIft2H ┆ 0.180283  ┆ 0.000023  ┆ 0.000028  ┆ … ┆ 0.000019  ┆ 1.410135  ┆ -0.290848 ┆ 0.293844 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:
modis_mod09ga = os.path.join(path2, 'processed_modis_mod09ga.parquet')
modis_mod09gadf = pl.read_parquet(modis_mod09ga)

modis_mod09gadf.head(5)

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ PID       ┆ sur_refl_ ┆ sur_refl_ ┆ sur_refl_ ┆ … ┆ BSI_mod09 ┆ GEMI_mod0 ┆ ARVI_mod0 ┆ SIPI_mod │
│ ---       ┆ b01       ┆ b02       ┆ b03       ┆   ┆ ga        ┆ 9ga       ┆ 9ga       ┆ 09ga     │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ID_I5RGjv ┆ 0.00002   ┆ 0.000027  ┆ 0.000015  ┆ … ┆ 0.08098   ┆ 0.000101  ┆ 0.035892  ┆ 1.73743  │
│ ID_8jWzJ5 ┆ 0.000028  ┆ 0.000035  ┆ 0.000027  ┆ … ┆ -0.00746  ┆ 0.000132  ┆ 0.075058  ┆ 1.230892 │
│ ID_d009mj ┆ 0.000016  ┆ 0.0000251 ┆ 0.000007  ┆ … ┆ 0.157051  ┆ 0.000091  ┆ -0.006137 ┆ 2.034792 │
│ ID_2ymCjP ┆ 0.0000152 ┆ 0.000025  ┆ 0.000006  ┆ … ┆ 0.162345  ┆ 0.00009   ┆ 0.012441  ┆ 1.93659  │
│ ID_YIft2H ┆ 0.000017  ┆ 0.000025  ┆ 0.000007  ┆ … ┆ 0.151507  ┆ 0.000092  ┆ -0.0206   ┆ 2.126202 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [8]:
modis_mod13q1 = os.path.join(path2, 'processed_modis_mod13q1.parquet')
modis_mod13q1df = pl.read_parquet(modis_mod13q1)

modis_mod13q1df.head(5)

shape: (5, 19)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ PID       ┆ season_si ┆ season_co ┆ EVI_scale ┆ … ┆ NRI_appro ┆ PSRI_m13q ┆ SIPI_m13q ┆ MSI_m13q │
│ ---       ┆ n         ┆ s         ┆ d         ┆   ┆ x_m13q1   ┆ 1         ┆ 1         ┆ 1        │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ID_I5RGjv ┆ -0.977848 ┆ 0.209315  ┆ 0.000012  ┆ … ┆ 0.539747  ┆ 0.398224  ┆ -2.181982 ┆ 0.879645 │
│ ID_8jWzJ5 ┆ -0.977848 ┆ 0.209315  ┆ 0.000012  ┆ … ┆ 0.565194  ┆ 0.4       ┆ -2.13211  ┆ 0.865404 │
│ ID_d009mj ┆ -0.977848 ┆ 0.209315  ┆ 0.000013  ┆ … ┆ 0.532764  ┆ 0.340355  ┆ -0.978622 ┆ 0.992978 │
│ ID_2ymCjP ┆ -0.977848 ┆ 0.209315  ┆ 0.000013  ┆ … ┆ 0.566122  ┆ 0.368501  ┆ -1.052004 ┆ 0.995825 │
│ ID_YIft2H ┆ -0.977848 ┆ 0.209315  ┆ 0.00001   ┆ … ┆ 0.541339  ┆ 0.426662  ┆ -1.602378 ┆ 0.990503 │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [9]:
modis_mod16a2 = os.path.join(path2, 'processed_modis_mod16a2.parquet')
modis_mod16a2df = pl.read_parquet(modis_mod16a2)

modis_mod16a2df.head(5)

shape: (5, 5)
┌───────────┬──────┬──────┬─────────────┬─────────────┐
│ PID       ┆ ET   ┆ PET  ┆ ESI_mod16a2 ┆ ETD_mod16a2 │
│ ---       ┆ ---  ┆ ---  ┆ ---         ┆ ---         │
│ str       ┆ f64  ┆ f64  ┆ f64         ┆ f64         │
╞═══════════╪══════╪══════╪═════════════╪═════════════╡
│ ID_UgzkN8 ┆ 0.09 ┆ 5.99 ┆ 0.015025    ┆ 5.9         │
│ ID_d009mj ┆ 0.09 ┆ 6.04 ┆ 0.014901    ┆ 5.95        │
│ ID_2ymCjP ┆ 0.13 ┆ 5.96 ┆ 0.021812    ┆ 5.83        │
│ ID_YIft2H ┆ 0.09 ┆ 5.94 ┆ 0.015152    ┆ 5.85        │
│ ID_ZaKEFI ┆ 0.1  ┆ 5.89 ┆ 0.016978    ┆ 5.79        │
└───────────┴──────┴──────┴─────────────┴─────────────┘

In [12]:
sentinel1 = os.path.join(path2, 'processed_sentinel1.parquet')
sentinel1df = pl.read_parquet(sentinel1)

sentinel1df.head(5)

shape: (5, 7)
┌───────────┬──────────────┬──────────────┬────────────┬──────────────┬──────────────┬─────────────┐
│ PID       ┆ VH_to_VV_Rat ┆ VV_minus_VH_ ┆ Span_dB    ┆ instrumentMo ┆ orbitPropert ┆ relativeOrb │
│ ---       ┆ io_dB        ┆ dB           ┆ ---        ┆ de           ┆ ies_pass     ┆ itNumber_st │
│ str       ┆ ---          ┆ ---          ┆ f64        ┆ ---          ┆ ---          ┆ art         │
│           ┆ f64          ┆ f64          ┆            ┆ str          ┆ str          ┆ ---         │
│           ┆              ┆              ┆            ┆              ┆              ┆ f64         │
╞═══════════╪══════════════╪══════════════╪════════════╪══════════════╪══════════════╪═════════════╡
│ ID_7aZMWw ┆ -15.285084   ┆ 15.285039    ┆ -10.094365 ┆ IW           ┆ DESCENDING   ┆ 50.0        │
│ ID_7aZMWw ┆ -12.829261   ┆ 12.829231    ┆ -8.191884  ┆ IW           ┆ DESCENDING   ┆ 50.0        │
│ ID_7aZMWw ┆ -10.935327   ┆ 10.935278    ┆ -10.210975 ┆ IW           ┆ DESCENDING   ┆ 50.0        │
│ ID_ol90Qm ┆ -16.70001    ┆ 16.699964    ┆ -10.154771 ┆ IW           ┆ DESCENDING   ┆ 50.0        │
│ ID_ol90Qm ┆ -12.391998   ┆ 12.391947    ┆ -10.468678 ┆ IW           ┆ DESCENDING   ┆ 50.0        │
└───────────┴──────────────┴──────────────┴────────────┴──────────────┴──────────────┴─────────────┘

In [13]:
sentinel1df.tail(5)

shape: (5, 7)
┌───────────┬──────────────┬──────────────┬───────────┬──────────────┬──────────────┬──────────────┐
│ PID       ┆ VH_to_VV_Rat ┆ VV_minus_VH_ ┆ Span_dB   ┆ instrumentMo ┆ orbitPropert ┆ relativeOrbi │
│ ---       ┆ io_dB        ┆ dB           ┆ ---       ┆ de           ┆ ies_pass     ┆ tNumber_star │
│ str       ┆ ---          ┆ ---          ┆ f64       ┆ ---          ┆ ---          ┆ t            │
│           ┆ f64          ┆ f64          ┆           ┆ str          ┆ str          ┆ ---          │
│           ┆              ┆              ┆           ┆              ┆              ┆ f64          │
╞═══════════╪══════════════╪══════════════╪═══════════╪══════════════╪══════════════╪══════════════╡
│ ID_aUAOl1 ┆ -3.071579    ┆ 3.071514     ┆ -9.961505 ┆ IW           ┆ DESCENDING   ┆ 152.0        │
│ ID_6qaAmn ┆ -9.369612    ┆ 9.369609     ┆ 1.254704  ┆ IW           ┆ DESCENDING   ┆ 152.0        │
│ ID_6qaAmn ┆ -10.152603   ┆ 10.1526      ┆ 1.771697  ┆ IW           ┆ DESCENDING   ┆ 152.0        │
│ ID_6qaAmn ┆ -9.840534    ┆ 9.84053      ┆ 0.356553  ┆ IW           ┆ DESCENDING   ┆ 152.0        │
│ ID_6qaAmn ┆ -10.304796   ┆ 10.304792    ┆ 1.109458  ┆ IW           ┆ DESCENDING   ┆ 152.0        │
└───────────┴──────────────┴──────────────┴───────────┴──────────────┴──────────────┴──────────────┘

In [15]:
sentinel2 = os.path.join(path2, 'processed_sentinel2.parquet')
sentinel12df = pl.read_parquet(sentinel2)
sentinel12df.head(5)

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ PID       ┆ NDVI_sent ┆ EVI_sent2 ┆ SAVI_sent ┆ … ┆ BSI_sent2 ┆ NDRE2_sen ┆ CLOUDY_PI ┆ NODATA_P │
│ ---       ┆ 2         ┆ ---       ┆ 2         ┆   ┆ ---       ┆ t2        ┆ XEL_PERCE ┆ IXEL_PER │
│ str       ┆ ---       ┆ f64       ┆ ---       ┆   ┆ f64       ┆ ---       ┆ NTAGE     ┆ CENTAGE  │
│           ┆ f64       ┆           ┆ f64       ┆   ┆           ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ ID_ZaKEFI ┆ 0.111719  ┆ 0.081204  ┆ 0.084783  ┆ … ┆ 0.21135   ┆ 0.052423  ┆ 0.000693  ┆ 0.0      │
│ ID_ZaKEFI ┆ 0.112346  ┆ 0.079281  ┆ 0.084579  ┆ … ┆ 0.210319  ┆ 0.054399  ┆ 0.000693  ┆ 0.0      │
│ ID_xFLwnc ┆ 0.122068  ┆ 0.076169  ┆ 0.091825  ┆ … ┆ 0.255157  ┆ 0.045639  ┆ 0.000693  ┆ 0.0      │
│ ID_xFLwnc ┆ 0.135552  ┆ 0.086058  ┆ 0.100927  ┆ … ┆ 0.241437  ┆ 0.055711  ┆ 0.000693  ┆ 0.0      │
│ ID_9uA1am ┆ 0.165208  ┆ 0.095413  ┆ 0.104667  ┆ … ┆ 0.267179  ┆ 0.086861  ┆ 0.000693  ┆ 0.0      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘